language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_install:


script:
  - ./gradlew clean asciidoctor -i
  - ./gradlew publish -i -PghToken=${GH_TOKEN}

after_script:
  - cd ..
  - git clone --branch=gh-pages git://github.com/danhyun/git-2015-session.git gh-pages
  - cd gh-pages
  - git config user.email "danhyun@users.noreply.github.com"
  - git config user.name "Dan hyun"
  - git rm -rf .
  - mv ../git-2015-session/build/asciidoctor/revealjs .
  - git add .
  - git commit -m "Publishing github pages"
  - git push -f "https://${GH_TOKEN}@github.com/danhyun/git-2015-session.git" gh-pages > /dev/null 2>&1
