language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_install:
  - git fetch
  - git checkout -f master
  - git config user.email "danhyun@users.noreply.github.com"
  - git config user.name "Dan hyun"

before_script:
  - git remote -v
  - git branch -v

script:
  - ./gradlew clean asciidoctor -i
  - ./gradlew publish -i -PghToken=${GH_TOKEN}
