language: java

jdk:
  - oraclejdk8

os:
  - linux

branches:
  only:
    - master

cache:
  directories:
  - $HOME/.gradle

before_script:
  - git fetch --unshallow
  - git checkout master

script:
  - ./gradlew clean asciidoctor -i
  - ./gradlew publish -i -PghToken=${GH_TOKEN}
