= Git Training
Dan Hyun <https://github.com/danhyun[@danhyun]>
2015-03-10

////
Topics to cover
the core concepts
differences from SVN
best practices
process
tools
migration
////

== Topics

* Introduction
* Git Fundamentals
* Git Commands
* Everyday Git
* Best Practices
* Resources


include::01-git-intro.adoc[]

include::02-git-fundamentals.adoc[]

include::03-git-basic-commands.adoc[]

== Typical local workflow

== Skipping `git add`

----
$ git commit --all -m "#yolo"
----

== Undoing commit

== .gitignore

== Collaborting

== git push

=== `push`

== git add gotcha

When modifying an added file, you'll need to re-add to stage the latest changes otherwise they won't make the commit.

Demonstrate git add stuff, demonstrate `git commit -am`

== reverting work

show how to reset files to previous version

== git stash

show how stashing works

== conflicts

show how conflicts work

introduce merge, fetch, pull, remote update rebasing

== Best practices

TIP: Use command line initially to get a feel for the rhythm/terminology

* Use commandline exclusively in the beginning
* Adhere to your team's work flow

=== git commit

make good commit message

use present tense and one line summary < 50 chars

add paragraph with more details

== Two workflows

* Develop -> Staging -> Master
* Commit to master

== Resources

http://scottchacon.com/2011/08/31/github-flow.html[Git Flow]:: Blog article by Scott Chacon about a workflow
http://git-scm.com/book/en/v2[Pro Git]:: Free ebook by Scott Chacon (Github) and Ben Straub
http://gitimmersion.com/[Git Immersion]:: Series of labs to learn git fundamentals
https://www.youtube.com/watch?v=4XpnKHJAok8[Linus Torvalds on git]:: Video - Linus talks about git

=== Resources

http://www.ndpsoftware.com/git-cheatsheet.html[Interactive git cheat sheet]
http://nvie.com/posts/a-successful-git-branching-model/[Suggested git branching model]

== Questions?
